spring:
  datasource:
    url: jdbc:postgresql://hr-users-pg12:5432/hr_users
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    service-url:
      defaultZone: http://hr-eureka-server:8761/eureka