spring.jpa.properties.javax.persistence.schema-generation:
  create-source: metadata
  scripts:
    action: create
    create-target: create.sql

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_users
    username: postgres
    password: 1234567
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        hbm2ddl.delimiter: ;
        jdbc:
          lob:
            non_contextual_creation: true