spring:
  datasource:
    url: jdbc:postgresql://hr-worker-pg12:5432/hr_worker
    username: postgres
    password: 1234567
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true