spring:
  application:
    name: hr-payroll

server:
  port: 8101

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

hr-worker:
  ribbon:
    listOfServers: localhost:8001, localhost:8002