spring:
  application:
    name: hr-worker
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${PORT:8001}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics