spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: ${GIT_BRANCH:master}
          uri: ${GIT_CONFIG_REPO:https://github.com/luanelioliveira/ms-humanresources}
          username: ${GIT_USERNAME:}
          password: ${GIT_PASSWORD:}

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, metrics