spring:
  application:
    name: hr-gateway-server

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    worker:
      service-id: hr-worker
      path: /hr-worker/**
    payroll:
      service-id: hr-payroll
      path: /hr-payroll/**
    users:
      service-id: hr-users
      path: /hr-users/**
    auth:
      service-id: hr-auth
      path: /hr-auth/**
      sensitive-headers: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

management:
  endpoints:
    web:
      exposure:
        include: health, metrics